version: "3"
services:

  peer-0:
    build: .
    container_name: elixir-node-0
    command:
      -e "Aecore.Miner.Worker.resume()"

  peer-1:
    build: .
    container_name: elixir-node-1
    depends_on:
      - peer-0
    command:
      -e "Aecore.Peers.Worker.get_info_try_connect(\"elixir-node-0:4000\")"
      -e "Aecore.Miner.Worker.resume()"

  peer-2:
    build: .
    container_name: elixir-node-2
    depends_on:
      - peer-0
    command:
      -e "Aecore.Peers.Worker.get_info_try_connect(\"elixir-node-0:4000\")"
